# Generated by Django 5.1.4 on 2024-12-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menuitem_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='Restaurant_name',
            new_name='name',
        ),
    ]
